### PR TITLE
Updated Nuget packages

### PR DESCRIPTION
**Pull request by cmatskas**
Updated ScriptCs to latest and all NuGet packages in the test projects.
No other change has been done to the core configR project

### CODE REVIEW

**Comment by cmatskas** [comment]
@adamralph any chance you could have a look at this? It seems to be related to the update to the NuGet packages? I don't see much from the TeamCity build log. Oh, and why not AppVeyor??

**Comment by adamralph** [comment]
@cmatskas it's because of these lines https://github.com/cmatskas/config-r/blob/af4f03234b413fc59907e172a606e1867fab38e1/rakefile.rb#L9-L10. The paths need to be updated because of the version changes.

I use AppVeyor for some OSS projects (generally the newer ones) and CodeBetter CI for others (generally the older ones). I'm not really sure which I prefer. One one hand CodeBetter CI is overloaded and the UI really drags sometimes, on the other hand, AppVeyor can have some horrible queueing times.

**Comment by cmatskas** [comment]
@adamralph self referencing NuGet.exe error in the build? hmmm

**Comment by adamralph** [comment]
@cmatskas argh! Yes, they broke this somewhere between 2.8.3 and 2.8.6.

I had the same problem over at xbehave, see https://github.com/xbehave/xbehave.net/commit/48a9d72041a9b13a874b114d8598fd058e551ac5

I had to uninstall NuGet.CommandLine from the solution and stick the exe in a special folder instead. Such a fail :unamused:

**Comment by cmatskas** [comment]
@adamralph ok. So how do we fix this? Suggestions? Sorry for being such a pain. I feel I get you involved on every stage of this PR.. feels wrong :(

**Comment by adamralph** [comment]
@cmatskas no problem. You should be able to the same as I did for xbehave:

* Copy NuGet.exe from packages/NuGet.CommandLine into src/.nuget
* Uninstall NuGet.CommandLine from the solution
* Update the rake file with the new path
* Simplify the .gitignore, see https://github.com/xbehave/xbehave.net/commit/48a9d72041a9b13a874b114d8598fd058e551ac5#diff-a084b794bc0759e7a6b77810e01874f2

**Comment by cmatskas** [comment]
@adamralph and still failing...arg

**Comment by adamralph** [comment]
@cmatskas it's because you changed the obsolete violations from errors to warnings in Debug only, not in Release.

I added the extra line, squashed the commits into one and merged to the dev branch. You are now officially a ConfigR contributor! :trophy:

BTW - the commits had some other email address, not connected to your GitHub account. I fixed it for the squashed commit.

**Pull request closed without merging**
