### PR TITLE
Remove json.net dependency

### PR DESCRIPTION
**Pull request by cmatskas**
@adamralph as discussed on issue #216, I've removed this dependency :)

### CODE REVIEW

**Comment by adamralph** [comment]
Thanks @cmatskas! The changes look perfect :ok_hand: 

There's a slight problem in the commits though. For some reason there is a `--no-ff` merge from upstream dev to your dev. The PR branch should be a straight line of commits (just one in this case) from the upstream dev branch.

BTW - you're still committing using an email address which doesn't match your GitHub account so GitHub is unable to tie the commit back to your account.

**Comment by cmatskas** [comment]
@adamralph email - fixed (i'm in the office so GitHub decided to use my local account for some reason). As for the --no-ff, I branched off dev this morning, set my upstream and did my changes. This is a bit odd. Can you work around it? Thanks

**Comment by adamralph** [comment]
@cmatskas you can configure your email address for each repo separately, so you can keep your work email address for work repos and switch to your private email address for stuff you push to GitHub.

I'll cherry pick the commit and merge it to dev (and fix your email address :wink:).

**Comment by cmatskas** [comment]
Thanks :+1:  :wink:

**Comment by cmatskas** [comment]
Did you ever get a chance to pull this? Can we merge and close? thanks

**Comment by adamralph** [comment]
@cmatskas thanks for reminding me and sorry for the delay. I cherry picked your commit into #220

**Pull request closed without merging**
