### PR TITLE
remove Configurator.cs #192

### PR DESCRIPTION
**Pull request by teabaggs**
removed configurator.cs per https://github.com/config-r/config-r/issues/192
also added *.TMP to .gitignore. sublime text-leaves a lot of temp files around. I suppose I should clean them up, but just in case

connects to #192

### CODE REVIEW

**Comment by teabaggs** [comment]
not sure exactly why the build failed since I cannot access team city and my rake output seems fine. If you can let me know, I'll be happy to fix it. 
Thanks
```
All packages listed in packages.config are already installed.
All packages listed in packages.config are already installed.
  ConfigR -> C:\Users\rop1mtp\Documents\GitHub\config-r\src\ConfigR\bin\Release\ConfigR.dll
  ConfigR.Testing.Service -> C:\Users\rop1mtp\Documents\GitHub\config-r\src\test\ConfigR.Testing.Service\bin\Release\ConfigR.Testing.Service.exe
  ConfigR.Testing.VSHostingProcess -> C:\Users\rop1mtp\Documents\GitHub\config-r\src\test\ConfigR.Testing.VSHostingProcess\bin\Release\ConfigR.Testing.VSHostingProcess.exe
  ConfigR.Testing.Website -> C:\Users\rop1mtp\Documents\GitHub\config-r\src\test\ConfigR.Testing.Website\bin\ConfigR.Testing.Website.dll
  ConfigR.Testing.External -> C:\Users\rop1mtp\Documents\GitHub\config-r\src\test\ConfigR.Testing.External\bin\Release\ConfigR.Testing.External.dll
  ConfigR.Features -> C:\Users\rop1mtp\Documents\GitHub\config-r\src\test\ConfigR.Features\bin\Release\ConfigR.Features.dll
xUnit.net console test runner (64-bit .NET 4.0.30319.42000)
Copyright (C) 2015 Outercurve Foundation.

Discovering: ConfigR.Features
Discovered:  ConfigR.Features
Starting:    ConfigR.Features
Finished:    ConfigR.Features

=== TEST EXECUTION SUMMARY ===
   ConfigR.Features  Total: 206, Errors: 0, Failed: 0, Skipped: 0, Time: 3.750s
Attempting to build package from 'ConfigR.csproj'.
Packing files from 'C:\Users\rop1mtp\Documents\GitHub\config-r\src\ConfigR\bin\Release'.
Using 'ConfigR.nuspec' for metadata.
Found packages.config. Using packages listed as dependencies
Successfully created package 'artifacts/output\ConfigR.0.13.0.nupkg'.
D, [2015-10-03T13:05:23.991188 #17152] DEBUG -- : Executing Exec: "C:/Program Files (x86)/MSBuild/12.0/Bin/MSBuild.exe" src/ConfigR.sln /target:Clean /p:configuration=Release /nr:false /verbosity:minimal /nologo /fl /flp:LogFile=artifacts/logs/Clean.log;Verbosity=Detailed;PerformanceSummary
D, [2015-10-03T13:05:24.397201 #17152] DEBUG -- : Executing Exec: "C:/Users/rop1mtp/Documents/GitHub/config-r/src/packages/NuGet.CommandLine.2.8.3/tools/NuGet.exe" restore src/ConfigR.sln
D, [2015-10-03T13:05:24.605721 #17152] DEBUG -- : Executing Exec: "C:/Program Files (x86)/MSBuild/12.0/Bin/MSBuild.exe" src/ConfigR.sln /target:Build /p:configuration=Release /nr:false /verbosity:minimal /nologo /fl /flp:LogFile=artifacts/logs/Build.log;Verbosity=Detailed;PerformanceSummary
D, [2015-10-03T13:05:27.621241 #17152] DEBUG -- : Executing XUnit: "C:/Users/rop1mtp/Documents/GitHub/config-r/src/packages/xunit.runner.console.2.0.0/tools/xunit.console.exe" src/test/ConfigR.Features/bin/Release/ConfigR.Features.dll -html C:/Users/rop1mtp/Documents/GitHub/config-r/src/test/ConfigR.Features/bin/Release/ConfigR.Features.dll.TestResults.html -xml C:/Users/rop1mtp/Documents/GitHub/config-r/src/test/ConfigR.Features/bin/Release/ConfigR.Features.dll.TestResults.xml
D, [2015-10-03T13:05:32.102416 #17152] DEBUG -- : Executing Exec: "C:/Users/rop1mtp/Documents/GitHub/config-r/src/packages/NuGet.CommandLine.2.8.3/tools/NuGet.exe" pack src/ConfigR/ConfigR.csproj -Version 0.13.0 -OutputDirectory artifacts/output -NoPackageAnalysis -Properties Configuration=Release

```

**Comment by adamralph** [comment]
@teabaggs thanks for this!

There are a couple of problems:

* You removed the .cs file but you didn't remove it from the project. This is why the build is failing.
> [19:51:24][Execute build] CSC : error CS2001: Source file 'Configurator.cs' could not be found [Z:\Builds\work\9e41d2b3a2c4c050\src\ConfigR\ConfigR.csproj]

* You've merged the upstream dev branch into your dev branch which has created a messy history, see https://github.com/config-r/config-r/network. Please see https://github.com/config-r/config-r/blob/dev/CONTRIBUTING.md - each PR branch should be a straight line of commits from the dev branch. This point isn't vital, I can always just cherry pick your commits, but it's simpler if I'm able to just push the green button on the PR.

BTW - you should be able to view the build by selecting 'Log in as guest' or by creating an account.

**Comment by teabaggs** [comment]
Hi Adam,

Sorry for the delay in getting to this but we should be all good now. I think I made the [network](https://github.com/config-r/config-r/network) worse but I'm pretty sure I know what the heck I *should* be doing now.

**Comment by teabaggs** [comment]
Hi Adam,

So considering your notes and my slightly improved understanding of git I
am wondering if it is worth it to rollback everything and start over? there
are 4 changes and 1 is a delete and I can get the clean history we're
looking for. Just to be sure though I should pull the upstream dev into my
branch before i reabse this to dev, then my dev has latest upstream/dev
plus my changes? then create the PR, right? Thanks for the tips, BTW.

**Comment by adamralph** [comment]
Hi @teabaggs 

Yep, I think it's probably best to create a new PR from a clean branch. It's probably best to reset your dev branch to the latest upstream dev commit, keeping your changes, create a new branch and then commit.

It would be good if you could also revert the changes to `src/test/ConfigR.Features/AnonymousTypesFeature.cs`.

The addition of `*.TMP` to `.gitignore` isn't related but I don't mind it being part of the change set. Out of interest, what are these TMP files you're seeing? I use sublime sometimes I don't see these.

E.g. (assuming you have an "origin" remote pointing to your fork and an "upstream" remote pointing to this repo)

* `git remote update`
* `git checkout dev`
* `git reset upstream/dev --mixed`
* `git checkout -b 192-remove-obsoletes`
* `git checkout src/test/ConfigR.Features/AnonymousTypesFeature.cs`
* `git commit -a -m "remove Configurator"`
* `git push origin 192-remove-obsoletes`
* raise PR from `192-remove-obsoletes` branch
* *Optional, if you want to tidy up your fork*
  * `git checkout dev`
  * `git push origin dev -f`

For future reference, the main thing that will make life easier next time round is to remember never to commit to the `dev` branch. Always commit to a branch. More info at https://github.com/config-r/config-r/blob/dev/CONTRIBUTING.md#making-changes

**Comment by adamralph** [comment]
superseded by #208

**Pull request closed without merging**
