### PR TITLE
update simple-targets-csx to 5.3.0

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by filipw** [comment]
Thanks - should we try the new CMD package here too?

**Comment by adamralph** [comment]
Sure, same PR or a separate one?

**Comment by filipw** [comment]
maybe you could add it to this one? whatever works for you though

**Comment by adamralph** [comment]
Sure, I'll add it here.

**Comment by adamralph** [comment]
Actually, SimpleExec doesn't provide the reading of the stdout yet, so it would only be a "half" fix, since it can't yet replace `ReadCmd`. I suggest you merge this as-is, and when I've added that to SimpleExec I'll raise another PR to replace both `Cmd` and `ReadCmd`.

**Comment by filipw** [comment]
ah cool 👍

**Comment by adamralph** [comment]
Having said that, once you've switched to the SDK-style csproj, we can drop `vswhere` which would remove the need for `ReadCmd`, so probably better to wait until then and then switch to `SimpleExec` as-is.

**Pull request merged**
